# Generated by Django 5.0.7 on 2024-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
